services: 
  frontend:
    build: ./Frontend_BD
    container_name: frontend
    ports: 
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - Ciruela
    restart: always
  
  backend:
    build: ./Backend_BD
    container_name: backend
    ports: 
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: Obligatorio
      DB_APP_USER: ucurooms_app
      DB_APP_PASSWORD: ucurooms_password
      DB_ADMIN_USER: ucurooms_admin
      DB_ADMIN_PASSWORD: admin_pass
      DB_FUNC_USER: ucurooms_funcionario
      DB_FUNC_PASSWORD: funcionario_pass
      DB_PART_USER: ucurooms_participante
      DB_PART_PASSWORD: participante_pass
      DB_LOGIN: ucurooms_login
      DB_LOGIN_PASSWORD: login_pass
      SECRET_KEY: super_clave_ultra_secreta_que_no_se_comparta
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      PYTHONIOENCODING: utf-8
    command: flask run --host=0.0.0.0 --debug
    networks:
      - Ciruela
    restart: always
    
  db:
    image: mysql:8.0
    container_name: Obligatorio
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Obligatorio
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]
    ports:
      - "3307:3306"
    networks:
      - Ciruela
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro 

networks:
  Ciruela:
